version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sql_c
    environment:
      - MYSQL_ROOT_PASSWORD=Utec
    ports:
      - "8005:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:latest
    container_name: postgres_c
    environment:
      - POSTGRES_PASSWORD=Utec
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: mongo_c
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  postgres_data:
  mongo_data: